services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  livekit:
    image: livekit/livekit-server
    command: --config /etc/livekit.yaml --node-ip 0.0.0.0 --redis-host redis:6379 --bind 0.0.0.0
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "50000-50100:50000-50100/udp" # RTC port range for debugging
    environment:
      - LIVEKIT_LOG_LEVEL=debug
    depends_on:
      redis:
        condition: service_started
  sip:
    image: livekit/sip
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    environment:
      SIP_CONFIG_BODY: |
        api_key: 'devkey'
        api_secret: 'secret'
        ws_url: 'ws://livekit:7880'
        redis:
          address: 'redis:6379'
        sip_port: 5060
        rtp_port_range: 10000-20000
        use_external_ip: false
        logging:
          level: debug
        bind_address: "0.0.0.0"
        public_ip: "172.23.126.232"
        allow_anonymous: true

volumes:
  redis_data:


networks:
  default:
    name: stimm-network
    external: true
