services:
  stimm-front:
    build:
      context: ../../src/front
      dockerfile: ../../docker/stimm-front/Dockerfile.dev
    container_name: stimm-front
    volumes:
      - ../../src/front:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_HOSTNAME=stimm
      - NEXT_PUBLIC_LIVEKIT_HOSTNAME=livekit
    # Environment variables are loaded from env_file in root docker-compose.yml
    stdin_open: true
    tty: true
